# 基础镜像的Dockerfile ： https://lark.alipay.com/aone/docker/rm2g1d
# 基于基础镜像
FROM reg.docker.alibaba-inc.com/ali/os:6u2

# 指定应用名字，配置在$APP_NAME.release文件里
# 从 build.tools.docker.args=--build-arg APP_NAME=${APP_NAME} 传入
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

# 指定pandora的版本
ARG sar_version=2018-01-release

# 构建时要做的事，一般是执行shell命令，例如用来安装必要软件，创建文件（夹），修改文件
RUN rpm -ivh --nodeps "http://yum.corp.taobao.com/taobao/6/x86_64/current/ali-jdk/ali-jdk-8.2.3-739170.alios6.x86_64.rpm" && \
{ rpm -ivh --nodeps "http://yum.tbsite.net/taobao/6/x86_64/current/tengine-proxy/tengine-proxy-2.1.4-510366.el6u2.x86_64.rpm " || true; } && \
rpm -ivh --nodeps "http://yum.tbsite.net/taobao/6/x86_64/stable/taobao-cronolog/taobao-cronolog-1.7.0b-2.el6.x86_64.rpm" && \
rpm -ivh --nodeps "http://yum.tbsite.net/taobao/6/x86_64/current/c_tbip/c_tbip-2.0.5-18365.el6.x86_64.rpm" && \
mkdir -p /home/admin/$APP_NAME/target && \
wget -qc -O /home/admin/$APP_NAME/target/taobao-hsf.tgz "http://ops.jm.taobao.org:9999/pandora-web/sar/$sar_version/taobao-hsf.tgz" && \
echo "/home/admin/$APP_NAME/bin/appctl.sh stop" > /home/admin/stop.sh && \
echo "/home/admin/$APP_NAME/bin/appctl.sh restart" >> /home/admin/start.sh && \
echo "/home/admin/$APP_NAME/bin/preload.sh" > /home/admin/health.sh && \
chmod +x /home/admin/*.sh

# 检验sar包md5是否正确
RUN onlineMd5=`curl --silent "http://ops.jm.taobao.org:9999/pandora-web/api/getSar.do?version=${sar_version}" | grep -Po '(?<="md5":")[0-9a-z]+'`; \
    localMd5=`md5sum /home/admin/$APP_NAME/target/taobao-hsf.tgz | awk '{print $1}'`; \
    if [ "$onlineMd5" != "$localMd5" ]; then \
        echo "taobao-hsf.sar md5 check failed! expect $onlineMd5, but $localMd5"; \
        exit 1;  \
    fi


# 6u2的的镜像中的/sbin/init启动时会执行/etc/rc.d/rc,会导致rc3.d中的服务被重新触发一次启动,下面语句可解决两次重启问题
RUN echo "" > /etc/rc.d/rc

# 将应用nginx脚本复制到镜像中
COPY environment/common/cai/ /home/admin/cai/

# 将应用启动脚本和配置文件复制到镜像中
COPY environment/common/bin/ /home/admin/${APP_NAME}/bin

# 设置文件操作权限
RUN chmod -R a+x /home/admin/${APP_NAME}/bin/ /home/admin/cai/bin/

# 挂载数据卷,指定目录挂载到宿主机上面,为了能够保存（持久化）数据以及共享容器间的数据，为了实现数据共享，例如日志文件共享到宿主机或容器间共享数据.
VOLUME /home/admin/$APP_NAME/logs \
       /home/admin/logs \
       /home/admin/cai/logs \
       /home/admin/diamond \
       /home/admin/snapshots \
       /home/admin/configclient \
       /home/admin/notify \
       /home/admin/catserver \
       /home/admin/liaoyuan-out \
       /home/a/vipsrv-dns \
       /home/admin/vipsrv-failover \
       /home/admin/vipsrv-cache \
       /home/admin/csp \
       /home/admin/.rocketmq_offsets \
       /home/admin/amsdata \
       /home/admin/amsdata_all

# 启动容器时进入的工作目录
WORKDIR /home/admin/$APP_NAME/bin

#容器启动时自动执行的脚本，我们一般会将应用启动脚本放在这里，相当于系统自启应用
ENTRYPOINT ["/home/admin/start.sh"]
